services:
  app:
    build: .
    container_name: dokyard_app
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/clubdocker:/home/clubdocker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - pgdb_main
      - pgdb_user
#      - gitea
#    networks:
#      - caddy_net

  pgdb_main:
    image: postgres:17
    container_name: dokyard_main
    ports:
      - '5433:5432'
    volumes:
      - ./dokyard_main_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
      POSTGRES_USER: ${POSTGRES_MAIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MAIN_PASSWORD}
    env_file:
      - .env
    restart: always
    #    networks:
    #      - caddy_net

  pgdb_user:
    image: postgres:17
    container_name: dokyard_user
    ports:
      - '5432:5432'
    volumes:
      - ./dokyard_user_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    env_file:
      - .env
    restart: always
#    networks:
#      - caddy_net

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: dokyard_pgadmin
      depends_on:
        - pgdb_user
      ports:
        - "5050:5050"
      environment:
        PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_LISTEN_PORT:      ${PGADMIN_LISTEN_PORT}
      env_file:
        - .env
      volumes:
        - ./pgadmin_data:/var/lib/pgadmin
      restart: always

#  gitea-db:
#    image: postgres:16
#    container_name: dokyard_gitea_db
#    restart: always
#    environment:
#      POSTGRES_DB: gitea
#      POSTGRES_USER: gitea
#      POSTGRES_PASSWORD: gitea_pass
#    volumes:
#      - ./gitea_db:/var/lib/postgresql/data
#
#  gitea:
#    image: gitea/gitea:1.22.0-rootless  # версия с OCI-registry
#    container_name: dokyard_gitea
#    restart: always
#    depends_on: [ gitea-db ]
#    ports:
#      - "3000:3000"   # веб-UI
#      - "2222:22"     # git+ssh (необязательно, но удобно)
#    environment:
#      # — подключение к БД
#      - GITEA__DATABASE__DB_TYPE=postgres
#      - GITEA__DATABASE__HOST=gitea-db:5432
#      - GITEA__DATABASE__NAME=gitea
#      - GITEA__DATABASE__USER=gitea
#      - GITEA__DATABASE__PASSWD=gitea_pass
#
#      # — включаем пакеты и контейнеры
#      - GITEA__PACKAGES__ENABLED=true
#      - GITEA__PACKAGES__CONTAINERS__ENABLED=true
#      - GITEA__PACKAGES__CONTAINERS__ALLOWED_TYPES=docker,oci
#
#      # — URL вашего сервиса (важно для docker login)
#      - GITEA__SERVER__DOMAIN=${GITEA_DOMAIN}
#      - GITEA__SERVER__ROOT_URL=http://${GITEA_DOMAIN}/
#      - GITEA__SERVER__PROTOCOL=http
#    volumes:
#      - ./gitea_data:/data
#    env_file:
#      - .env

#  caddy:
#    image: caddy:latest
#    container_name: caddy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy_data:/data
#      - ./caddy_config:/config
#    environment:
#      - CADDY_EMAIL=mail@devspond.pro
#    networks:
#      - caddy_net
#
#volumes:
#  caddy_data:
#  caddy_config:
#
#networks:
#  caddy_net: