services:
  app:
    build: .
    container_name: dokyard_app
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/clubdocker:/home/clubdocker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - pgdb_main
#    networks:
#      - caddy_net

  pgdb_main:
    image: postgres:17
    container_name: dokyard_main
    ports:
      - '5433:5432'
    volumes:
      - ./dokyard_main_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
      POSTGRES_USER: ${POSTGRES_MAIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MAIN_PASSWORD}
    env_file:
      - .env
    restart: always
    #    networks:
    #      - caddy_net

  pgdb_user:
    image: postgres:17
    container_name: dokyard_user
    ports:
      - '5432:5432'
    volumes:
      - ./dokyard_user_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    env_file:
      - .env
    restart: always
#    networks:
#      - caddy_net

#  caddy:
#    image: caddy:latest
#    container_name: caddy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy_data:/data
#      - ./caddy_config:/config
#    environment:
#      - CADDY_EMAIL=mail@devspond.pro
#    networks:
#      - caddy_net
#
#volumes:
#  caddy_data:
#  caddy_config:
#
#networks:
#  caddy_net: